name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-package:
    name: Test package
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"
    steps:
      - uses: actions/checkout@v4
      - name: Test VRMKit
        run: set -o pipefail && make test-package | xcpretty

